[phases.setup]
nixPaths = ["python310", "nodejs-18_x"]

[phases.install]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "cd backend && python main.py"

[variables]
PYTHONUNBUFFERED = "1"
NODE_ENV = "production"